#!/bin/bash

# **************************************************************************************************/
#   ROCM-GDB Driver script
#
#   Copyright (c) 2015-2016 ADVANCED MICRO DEVICES, INC.  All rights reserved.
#   This file includes code originally published under
#
#   Copyright (C) 1986-2014 Free Software Foundation, Inc.
#
#   This file is part of GDB.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */
# ****************************************************************************************************

# Concatenate all arguments in a single variable
GDB_ARGS="$*"

# Get the full path to the script
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    TARGET="$( readlink "$SOURCE" )"
    if [[ $SOURCE == /* ]]; then
        SOURCE="$TARGET"
    else
        DIR="$( dirname "$SOURCE" )"
        SOURCE="$DIR/$TARGET"
    fi
done
REALPATH="$( dirname "$SOURCE" )"

# A wrapper script that calls rocm-gdb with just a dummy "SDK" name in the LD_LIBRARY_PATH
# Needed for someone else building gdb from github and using the Debug SDK which could be anywhere
#
# The rocm-gdb-local script will be copied to the build_debug / build_release locations and 
# shouldn't be run from the gdb-X.X/gdb/
#
# If you are using rocm-gdb-local, you need to set the LD_LIBRARY_PATH to point to
# the library location of the Debug SDK (i.e. AMDGPUKernelDebugSDK/lib/x86_64)
export LD_LIBRARY_PATH=/dummy/gpudebugsdk/lib/x86_64:$REALPATH/../../lib/x86_64:${LD_LIBRARY_PATH}
$REALPATH/rocm-gdb $GDB_ARGS
